### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by tciuro** [Apple-Actions/import-codesign-certs#6]
Hello,

Noob here. So I have the base64 file created from a password-protected p12 file. I see that I'm supposed to enter the following in the yaml file:

    uses: apple-actions/import-codesign-certs@v1
    with: 
      p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
      p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

Questions:

- Where in the YAML file should the above snippet go?
- Are these two attributes referring to a specific file? Or should I paste the contents of the file?
- If it's a file reference, where in the project should I place the two files?

Thanks!

**Comment by orj** [comment]
@tciuro Apologies for not providing more documentation. Note that this project is for a GitHub Action.  You should be familiar with [GitHub Actions](https://github.com/features/actions) in order to use it.

The YAML is your [GitHub Actions workflow](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions).  The attributes are making reference to [GitHub Action secrets](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets).

**Comment by dimitarnestorov** [comment]
The P12 file is a result of exporting your certificate from Keychain Access. This certificate requires you to set up a password hence the `p12-password`. This export is also a binary file and the GitHub Action secrets are strings so you will have to convert that binary in base64, and even though it is password protected I would still advise not to use online tools for the conversion.

**Comment by orj** [comment]
There is a command line too in macOS Catalina called `base64`.  You can do the conversion in terminal.  So once you've exported your Code Signing Certificate and Private Key from Keychain Access to a file named `Certificate.p12` you can run this command.

Eg:

```
cat Certificate.p12 | base64 | pbcopy
```

The above command line will put the base64 encoded `.p12` file into your Mac's Copy/Paste buffer so you can paste it into a GitHub Actions Secret which you can later feed into your workflow.

**Comment by tciuro** [comment]
Yup. I got it working! Thanks a lot for the help! 🤙🏻
